export const LOAD_CLIENTS = 'LOAD_CLIENTS';
export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID';
export const SET_CLIENTS = 'SET_CLIENTS';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const SHOW_CLIENTS_ERROR_MESSAGE = 'SHOW_CLIENTS_ERROR_MESSAGE';
export const HIDE_CLIENTS_ERROR_MESSAGE = 'HIDE_CLIENTS_ERROR_MESSAGE';
